openapi: 3.0.0

info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW-Authenticate:
          schema:
            type: string

security:
  - ApiKeyAuth: []

paths:
  /rules/{name}:
    get:
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        uri: ${lambda_arn}
        payloadFormatVersion: 1.0
      description: Returns a rule              
      parameters:
      - name: name
        in: path
        description: The name of the rule to request
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Not Found
        '500':
          description: Internal Error

