#!/bin/bash

rm -rf ../build
mkdir -p ../build/{extraction,user,rule}

cargo install cargo-lambda
cargo lambda build --release --arm64 --output-format zip

cp ./target/lambda/extraction_service/bootstrap.zip ../build/extraction/lambda.zip
cp ./target/lambda/user_service/bootstrap.zip ../build/user/lambda.zip
cp ./target/lambda/rule_service/bootstrap.zip ../build/rule/lambda.zip

