#!/bin/bash

rm -rf ./dist
mkdir ./dist

rustup target add x86_64-unknown-linux-musl
cargo build --release --target x86_64-unknown-linux-musl

cp ./target/x86_64-unknown-linux-musl/release/bootstrap ./bootstrap
zip -rj ./dist/lambda.zip ./bootstrap

rm ./bootstrap
