#!/bin/bash

rm -rf ./dist
mkdir ./dist

cargo install cargo-lambda cargo-zigbuild
cargo lambda build --release --arm64 --output-format zip

cp ./target/lambda/release/bootstrap.zip ./dist/bootstrap.zip
