#!/bin/bash

rm -rf ./dist
mkdir ./dist

docker run --platform arm64 --rm -v ${PWD}:/code -v ${HOME}/.cargo/registry:/root/.cargo/registry -v ${HOME}/.cargo/git:/root/.cargo/git rustserverless/lambda-rust:latest-arm64

cp ./target/lambda/release/bootstrap.zip ./dist/bootstrap.zip

rm ./bootstrap
