name: "Build"
on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install ziglang
        rustup toolchain install stable --profile minimal
      working-directory: ${{ env.GITHUB_WORKFLOW }}
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: ./build
      working-directory: ${{ env.GITHUB_WORKFLOW }}
    - name: Save Build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ env.GITHUB_WORKFLOW }}/dist
        retention-days: 1

