name: Build
on:
  workflow_call:
    inputs:
      directory: 
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install ziglang
        rustup toolchain install stable --profile minimal
      working-directory: ${{ inputs.directory }}
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: ./build
      working-directory: ${{ inputs.directory }}
    - name: Save Build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ inputs.directory }}/dist
        retention-days: 1
