name: "Deploy"

on:
  push:
    branches:
    - main
    paths:
    - backend/**
    - infrastructure/**
  pull_request:
    branches:
    - main
    paths:
    - backend/**
    - infrastructure/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install ziglang
        rustup toolchain install stable --profile minimal
      working-directory: backend
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: ./build
      working-directory: backend
    - name: Save Build
      uses: actions/upload-artifact@v3
      with:
        path: build
        retention-days: 1

  dev:
    needs: build
    uses: ./.github/workflows/deploy-env.yaml
    with:
      stage: dev
    secrets:
      role: ${{ secrets.ROLE }}
      gcp_identity_provider: ${{ secrets.GCP_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
