name: "Deploy Env"
on:
  workflow_call:
    inputs:
      stage:
        description: 'Stage to deploy'
        type: string
        required: true
      build:
        description: 'Whether or not there is a build artifact to be fetched'
        type: boolean
        default: true
        required: false
    secrets:
      role:
        description: 'Role to assume'
        required: true
      gcp_project:
        description: 'The project in gcp for dns'
        required: true
  
jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_GCP_PROJECT: ${{ secrets.gcp_project }}
      TF_DRY_RUN: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.role }}
        role-session-name: ${{ github.event.repository.name }}-${{ inputs.app }}-${{ inputs.stage }}
        aws-region: us-west-2
    - name: Fetch Build
      if: ${{ inputs.build }}
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ${{ github.workflow }}/dist
    - name: Deploy
      run: ./scripts/deploy ${{ github.workflow }} ${{ inputs.stage }}
