name: Deploy
on:
  workflow_call:
    inputs:
      stage:
        description: 'Stage to deploy'
        type: string
        required: true
      build:
        description: 'Whether or not there is a build artifact to be fetched'
        type: boolean
        default: true
        required: false
    secrets:
      role:
        description: 'Role to assume'
        required: true
      gcp_identity_provider:
        description: 'The OIDC identity provider in GCP'
        required: true
      gcp_service_account:
        description: 'The service account in GCP configured for the OIDC provider'
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_DRY_RUN: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.role }}
        role-session-name: ${{ github.event.repository.name }}-${{ inputs.stage }}
        aws-region: us-west-2
    - id: gcp_auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.gcp_identity_provider }}
        service_account: ${{ secrets.gcp_service_account }}
    - name: Deploy
      run: GOOGLE_APPLICATION_CREDENTIALS=${{ steps.gcp_auth.outputs.credentials_file_path }} ./scripts/deploy ${{ inputs.stage }}
