name: "parser"

on:
  push:
    branches:
    - main
    paths:
    - parser/**
    - .github/workflows/parser.yaml
    - .github/workflows/deploy-env.yaml
  pull_request:
    branches:
    - main
    paths:
    - parser/**
    - .github/workflows/parser.yaml
    - .github/workflows/deploy-env.yaml

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  dev:
    needs: build
    uses: ./.github/workflows/deploy-env.yaml
    with:
      stage: dev
    secrets:
      role: ${{ secrets.ROLE }}
      gcp_identity_provider: ${{ secrets.GCP_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
