name: "rules"

on:
  push:
    branches:
    - main
    paths:
    - rules/**
    - .github/workflows/rules.yaml
    - .github/workflows/deploy-env.yaml
    - .github/workflows/build.yaml
  pull_request:
    branches:
    - main
    paths:
    - rules/**
    - .github/workflows/rules.yaml
    - .github/workflows/deploy-env.yaml
    - .github/workflows/build.yaml

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  dev:
    needs: build
    uses: ./.github/workflows/deploy-env.yaml
    with:
      stage: dev
    secrets:
      role: ${{ secrets.ROLE }}
      gcp_project: ${{ secrets.GCP_PROJECT }}

